/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Entity.AddressInfo;
import Until.DBHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Hiba Habli
 */
public class AddressManager {
    DBHelper db;

    public AddressManager() throws Exception {
        this.db = new DBHelper();
    }
    
    public int createAddress(AddressInfo info) {
            try{
     String sql = "insert into Address (AddressLine1, AddressLine2, City, State, ZIP, Country, Type, CreditCardId)"
                 + " values('"+info.addressline1+"','"+info.addressline2+"','"+ info.city + "', '" + info.state 
                 + "','"+info.zip+"','"+info.country+"','"+info.Type+"','"+info.creditCardId+"')";

         return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }
}
