/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Entity.CommentInfo;
import Entity.SpeakerInfo;
import Until.DBHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hiba Habli
 */
public class CommentManager {
    DBHelper db;

    public CommentManager() throws Exception {
        this.db = new DBHelper();
    }
    
     public int createComment (CommentInfo info) {
        try {
            String sql = "insert into Comment (Name, Email, Comment)"
                    + " values(' " + info.name+ " ', ' "+info.email+" ', ' "+info.comment+" ' )";

            return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }
    
     public List<CommentInfo> listAll() throws Exception {
        List<CommentInfo> lst = new ArrayList<CommentInfo>();
        String sql = "select * from Comment";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            CommentInfo info = new CommentInfo();
            info.id = rs.getInt("Id");
            info.name = rs.getString("Name");
            info.date = rs.getString("Date");
            info.comment= rs.getString("Comment");
            lst.add(info);
        }
        return lst;
    }
     
}
