/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Entity.CreditCardInfo;
import Until.DBHelper;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.sql.SQLException;

/**
 *
 * @author Hiba Habli
 */
public class CreditCardManager {

    DBHelper db;

    public CreditCardManager() throws Exception {
        this.db = new DBHelper();
    }

    public int createCreditCard(CreditCardInfo info) {
        /**
         * try { String sql = "insert into credit_card(Number, ExpDate, " +
         * "SecurityCode, NameOnCard, Type)" + "values('" + info.number + "', '"
         * + info.expiration_date.toString() + "','" + info.security_code+ "','"
         * + info.name_on_card+ "', '" + info.card_type+ "'";
         */
        try {

            String sql1 = "select * from CreditCard where Number = '" + info.number + "'";
            ResultSet rs = this.db.getSQLResult(sql1);
            while (rs.next()) {
                int cardId = rs.getInt("Id");
                return cardId;
            }
            String sql = "insert into CreditCard (Number, ExpDate, SecurityCode, NameOnCard, Type)"
                    + " values('" + info.number + "','" + info.expiration_date + "','" + info.security_code + "','" + info.name_on_card + "', '" + info.card_type + "')";

            return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }
}
