/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Entity.PaperInfo;
import Entity.SessionInfo;
import Until.DBHelper;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Hiba Habli
 */
public class PaperManager {
     DBHelper db;

    public PaperManager() throws Exception {
        this.db = new DBHelper();
    }
    
    /**
     * list all the speakers
     *
     * @return list of speakers
     * @throws Exception
     */
     public int Addpaper(PaperInfo PI) {
        try {
            String sql = "insert into Paper ( Title, Description,  PaperFee, path)"
                    + " values( '" + PI.title + "' , '" + PI.description + "' , " + 50 + " ,'" + PI.path + "' )";

            return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }
     
     
      public List<PaperInfo> listAll() throws Exception {
        List<PaperInfo> lst = new ArrayList<PaperInfo>();
        String sql = "select * from Paper ORDER BY PaperId";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            PaperInfo info = new PaperInfo();
            info.PaperId= rs.getInt("PaperId");
            info.title = rs.getString("Title");
            info.description=rs.getString("Description");
           // info.UserId= rs.getInt("UserId");
            lst.add(info);
        }
        return lst;
    }
      

     
      public List<SessionInfo> listAllConference() throws Exception {
        List<SessionInfo> lst = new ArrayList<SessionInfo>();
        String sql = "select * from Session WHERE Type like 'Session' ORDER BY Type, Date, StartTime ASC";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            SessionInfo info = new SessionInfo();
            info.Id= rs.getInt("SessionId");
            info.title = rs.getString("Title");
            info.type = rs.getString("Type");
            info.fee = rs.getInt("Fee");
            info.date = rs.getString("Date");
            info.starttime = rs.getString("StartTime");
            info.endtime = rs.getString("EndTime");
            info.Id= rs.getInt("SessionId");
            lst.add(info);
        }
        return lst;
    }
      
         public List<SessionInfo> listAllTutorial() throws Exception {
        List<SessionInfo> lst = new ArrayList<SessionInfo>();
        String sql = "select * from Session WHERE Type like 'Tutorial' ORDER BY Type, Date, StartTime ASC ";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            SessionInfo info = new SessionInfo();
            info.Id= rs.getInt("SessionId");
            info.title = rs.getString("Title");
            info.type = rs.getString("Type");
            info.fee = rs.getInt("Fee");
            info.date = rs.getString("Date");
            info.starttime = rs.getString("StartTime");
            info.endtime = rs.getString("EndTime");
            info.Id= rs.getInt("SessionId");
            lst.add(info);
        }
        return lst;
    }
}
