

package Manager;

import Entity.UserInfo;
import Until.DBHelper;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.sql.SQLException;

/**
 *
 * @author Hiba Habli
 */
public class UserManager {

    DBHelper db;

    public UserManager() throws Exception {
        this.db = new DBHelper();
    }

    /**
     *
     * @param user
     * @return the userId that just created or -1 if error
     */
    public int registerUser(UserInfo user) throws Exception {
        try {
            String sql = "select * from User where email = '" + user.email + "'";
            ResultSet rs = this.db.getSQLResult(sql);
            while (rs.next()) {
                return -1;
            }
            sql = "insert into User(Email, Password) values('"
                    + user.email + "', '" + user.pswrd + "')";

            return this.db.executeSQL(sql).get(0);
        } catch (Exception ex) {
            throw ex;
        }
    }

      public List<UserInfo> listAll() throws Exception {
        List<UserInfo> lst = new ArrayList<UserInfo>();
        String sql = "select * from User ORDER BY UserId";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            UserInfo info = new UserInfo();
            info.id= rs.getInt("UserId");
            info.firstName = rs.getString("FirstName");
            info.lastName= rs.getString("LastName");
            lst.add(info);
        }
        return lst;
    }

    /**
     *
     * @param email
     * @param password
     * @return user or null if wrong email or password
     * @throws Exception
     */
    public UserInfo getUser(String email, String password) throws Exception {
        UserInfo user = null;
        String sql = "select * from User where Email = '" + email + "' and Password = '" + password + "'";
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            user = new UserInfo();
            user.id = rs.getInt("UserId");
            user.email = rs.getString("Email");
            user.pswrd = rs.getString("Password");
            user.firstName = rs.getString("FirstName");
            user.lastName = rs.getString("LastName");
        }
        return user;
    }

    /**
     * get the userInfo by an id
     *
     * @param id
     * @return user or null
     * @throws Exception
     */
    public UserInfo getUserById(int id) throws Exception {
        UserInfo user = null;
        String sql = "select * from User where UserId = " + id;
        ResultSet rs = this.db.getSQLResult(sql);
        while (rs.next()) {
            user = new UserInfo();
            user.id = id;
            user.email = rs.getString("Email");
            user.pswrd = rs.getString("Password");
            user.firstName = rs.getString("FirstName");
            user.lastName = rs.getString("LastName");
            user.phonnumber = rs.getString("PhoneNo");
            user.jobtitle = rs.getString("JobTitle");
            user.company = rs.getString("Company");

        }
        return user;
    }

    public int createUser(UserInfo user) {
        try {
            String sql = "insert into User (FirstName, LastName, Email, Password, Company, JobTitle, PhoneNo)"
                    + " values('" + user.firstName + "','" + user.lastName + "','" + user.email + "', '" + user.pswrd + "','"
                    + user.company + "','" + user.jobtitle + "','" + user.phonnumber + "')";

            return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }

    public int editUser(UserInfo user) {
        try {
            String sql = "Update User SET FirstName='" + user.firstName + "', LastName='"
                    + user.lastName + "', Email='" + user.email + "', Password='" + user.pswrd
                    + "', Company='" + user.company + "', JobTitle='" + user.jobtitle + "', PhoneNo='"
                    + user.phonnumber + "' WHERE UserId = " + user.id;

            this.db.executeSQL(sql);
            return 0;
        } catch (SQLException ex) {
            return -1;
        }
    }

    public int emailRegistered(String email) {
        try {
            UserInfo user = null;
            String sql = "select * from User where Email = " + email;
            ResultSet rs = this.db.getSQLResult(sql);
            while (rs.next()) {
                user = new UserInfo();
                user.email = rs.getString("Email");
                user.pswrd = rs.getString("Password");
                user.firstName = rs.getString("FirstName");
                user.lastName = rs.getString("LastName");
                user.phonnumber = rs.getString("PhoneNo");
                user.jobtitle = rs.getString("JobTitle");
                user.company = rs.getString("Company");

            }
            return -1;
        } catch (SQLException ex) {
            return 0;
        }
    }
}